[package]
name = "bittorrent-rust"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-rt = "2.8.0"
bincode = "1.3.3"
clap = {version = "4.3.0", features = ["derive"]}
crossterm = "0.26.1"
log = "0.4.17"
magnet-url = "2.0.0"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
serde = { version = "1.0.163", features = ["derive"] }
sha-1 = "0.10.1"
tokio = { version = "1.28.1", features = ["rt", "macros", "rt-multi-thread", "sync", "io-std", "io-util"] }
tui = "0.19.0"
urlencoding = "2.1.2"
