[package]
name = "bittorrent-rust"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.3.0", features = ["derive"]}
crossterm = "0.26.1"
log = "0.4.17"
pretty_env_logger = "0.5.0"
tokio = { version = "1.28.1", features = ["rt", "macros", "rt-multi-thread", "sync", "io-std", "io-util"] }
tui = "0.19.0"
